name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2.1.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test_tigknil
        run: ./test_tigknil
